version: '3'
services:
  # dotnet-api:
  #   build:
  #     context: ./dotnet
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development

  nuxt-app:
    build:
      context: ./dockerfiles/nuxt
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # depends_on:
    #   - dotnet-api