version: '3'
services:
  # dotnet-api:
  #   build:
  #     context: ./dotnet
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development

  nuxt-app:
    build:
      context: ./dockerfiles/nuxt
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 24678:24678 # HMR用のポートを追加
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - dotnet-api